<?php

use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert(['code' => 'AF', 'name' => 'Afghanistan']);
        DB::table('countries')->insert(['code' => 'AL', 'name' => 'Albania']);
        DB::table('countries')->insert(['code' => 'DZ', 'name' => 'Algeria']);
        DB::table('countries')->insert(['code' => 'DS', 'name' => 'American Samoa']);
        DB::table('countries')->insert(['code' => 'AD', 'name' => 'Andorra']);
        DB::table('countries')->insert(['code' => 'AO', 'name' => 'Angola']);
        DB::table('countries')->insert(['code' => 'AI', 'name' => 'Anguilla']);
        DB::table('countries')->insert(['code' => 'AQ', 'name' => 'Antarctica']);
        DB::table('countries')->insert(['code' => 'AG', 'name' => 'Antigua and Barbuda']);
        DB::table('countries')->insert(['code' => 'AR', 'name' => 'Argentina']);
        DB::table('countries')->insert(['code' => 'AM', 'name' => 'Armenia']);
        DB::table('countries')->insert(['code' => 'AW', 'name' => 'Aruba']);
        DB::table('countries')->insert(['code' => 'AU', 'name' => 'Australia']);
        DB::table('countries')->insert(['code' => 'AT', 'name' => 'Austria']);
        DB::table('countries')->insert(['code' => 'AZ', 'name' => 'Azerbaijan']);
        DB::table('countries')->insert(['code' => 'BS', 'name' => 'Bahamas']);
        DB::table('countries')->insert(['code' => 'BH', 'name' => 'Bahrain']);
        DB::table('countries')->insert(['code' => 'BD', 'name' => 'Bangladesh']);
        DB::table('countries')->insert(['code' => 'BB', 'name' => 'Barbados']);
        DB::table('countries')->insert(['code' => 'BY', 'name' => 'Belarus']);
        DB::table('countries')->insert(['code' => 'BE', 'name' => 'Belgium']);
        DB::table('countries')->insert(['code' => 'BZ', 'name' => 'Belize']);
        DB::table('countries')->insert(['code' => 'BJ', 'name' => 'Benin']);
        DB::table('countries')->insert(['code' => 'BM', 'name' => 'Bermuda']);
        DB::table('countries')->insert(['code' => 'BT', 'name' => 'Bhutan']);
        DB::table('countries')->insert(['code' => 'BO', 'name' => 'Bolivia']);
        DB::table('countries')->insert(['code' => 'BA', 'name' => 'Bosnia and Herzegovina']);
        DB::table('countries')->insert(['code' => 'BW', 'name' => 'Botswana']);
        DB::table('countries')->insert(['code' => 'BV', 'name' => 'Bouvet Island']);
        DB::table('countries')->insert(['code' => 'BR', 'name' => 'Brazil']);
        DB::table('countries')->insert(['code' => 'IO', 'name' => 'British Indian Ocean Territory']);
        DB::table('countries')->insert(['code' => 'BN', 'name' => 'Brunei Darussalam']);
        DB::table('countries')->insert(['code' => 'BG', 'name' => 'Bulgaria']);
        DB::table('countries')->insert(['code' => 'BF', 'name' => 'Burkina Faso']);
        DB::table('countries')->insert(['code' => 'BI', 'name' => 'Burundi']);
        DB::table('countries')->insert(['code' => 'KH', 'name' => 'Cambodia']);
        DB::table('countries')->insert(['code' => 'CM', 'name' => 'Cameroon']);
        DB::table('countries')->insert(['code' => 'CA', 'name' => 'Canada']);
        DB::table('countries')->insert(['code' => 'CV', 'name' => 'Cape Verde']);
        DB::table('countries')->insert(['code' => 'KY', 'name' => 'Cayman Islands']);
        DB::table('countries')->insert(['code' => 'CF', 'name' => 'Central African Republic']);
        DB::table('countries')->insert(['code' => 'TD', 'name' => 'Chad']);
        DB::table('countries')->insert(['code' => 'CL', 'name' => 'Chile']);
        DB::table('countries')->insert(['code' => 'CN', 'name' => 'China']);
        DB::table('countries')->insert(['code' => 'CX', 'name' => 'Christmas Island']);
        DB::table('countries')->insert(['code' => 'CC', 'name' => 'Cocos (Keeling) Islands']);
        DB::table('countries')->insert(['code' => 'CO', 'name' => 'Colombia']);
        DB::table('countries')->insert(['code' => 'KM', 'name' => 'Comoros']);
        DB::table('countries')->insert(['code' => 'CG', 'name' => 'Congo']);
        DB::table('countries')->insert(['code' => 'CK', 'name' => 'Cook Islands']);
        DB::table('countries')->insert(['code' => 'CR', 'name' => 'Costa Rica']);
        DB::table('countries')->insert(['code' => 'HR', 'name' => 'Croatia (Hrvatska)']);
        DB::table('countries')->insert(['code' => 'CU', 'name' => 'Cuba']);
        DB::table('countries')->insert(['code' => 'CY', 'name' => 'Cyprus']);
        DB::table('countries')->insert(['code' => 'CZ', 'name' => 'Czech Republic']);
        DB::table('countries')->insert(['code' => 'DK', 'name' => 'Denmark']);
        DB::table('countries')->insert(['code' => 'DJ', 'name' => 'Djibouti']);
        DB::table('countries')->insert(['code' => 'DM', 'name' => 'Dominica']);
        DB::table('countries')->insert(['code' => 'DO', 'name' => 'Dominican Republic']);
        DB::table('countries')->insert(['code' => 'TP', 'name' => 'East Timor']);
        DB::table('countries')->insert(['code' => 'EC', 'name' => 'Ecuador']);
        DB::table('countries')->insert(['code' => 'EG', 'name' => 'Egypt']);
        DB::table('countries')->insert(['code' => 'SV', 'name' => 'El Salvador']);
        DB::table('countries')->insert(['code' => 'GQ', 'name' => 'Equatorial Guinea']);
        DB::table('countries')->insert(['code' => 'ER', 'name' => 'Eritrea']);
        DB::table('countries')->insert(['code' => 'EE', 'name' => 'Estonia']);
        DB::table('countries')->insert(['code' => 'ET', 'name' => 'Ethiopia']);
        DB::table('countries')->insert(['code' => 'FK', 'name' => 'Falkland Islands (Malvinas)']);
        DB::table('countries')->insert(['code' => 'FO', 'name' => 'Faroe Islands']);
        DB::table('countries')->insert(['code' => 'FJ', 'name' => 'Fiji']);
        DB::table('countries')->insert(['code' => 'FI', 'name' => 'Finland']);
        DB::table('countries')->insert(['code' => 'FR', 'name' => 'France']);
        DB::table('countries')->insert(['code' => 'FX', 'name' => 'France, Metropolitan']);
        DB::table('countries')->insert(['code' => 'GF', 'name' => 'French Guiana']);
        DB::table('countries')->insert(['code' => 'PF', 'name' => 'French Polynesia']);
        DB::table('countries')->insert(['code' => 'TF', 'name' => 'French Southern Territories']);
        DB::table('countries')->insert(['code' => 'GA', 'name' => 'Gabon']);
        DB::table('countries')->insert(['code' => 'GM', 'name' => 'Gambia']);
        DB::table('countries')->insert(['code' => 'GE', 'name' => 'Georgia']);
        DB::table('countries')->insert(['code' => 'DE', 'name' => 'Germany']);
        DB::table('countries')->insert(['code' => 'GH', 'name' => 'Ghana']);
        DB::table('countries')->insert(['code' => 'GI', 'name' => 'Gibraltar']);
        DB::table('countries')->insert(['code' => 'GK', 'name' => 'Guernsey']);
        DB::table('countries')->insert(['code' => 'GR', 'name' => 'Greece']);
        DB::table('countries')->insert(['code' => 'GL', 'name' => 'Greenland']);
        DB::table('countries')->insert(['code' => 'GD', 'name' => 'Grenada']);
        DB::table('countries')->insert(['code' => 'GP', 'name' => 'Guadeloupe']);
        DB::table('countries')->insert(['code' => 'GU', 'name' => 'Guam']);
        DB::table('countries')->insert(['code' => 'GT', 'name' => 'Guatemala']);
        DB::table('countries')->insert(['code' => 'GN', 'name' => 'Guinea']);
        DB::table('countries')->insert(['code' => 'GW', 'name' => 'Guinea-Bissau']);
        DB::table('countries')->insert(['code' => 'GY', 'name' => 'Guyana']);
        DB::table('countries')->insert(['code' => 'HT', 'name' => 'Haiti']);
        DB::table('countries')->insert(['code' => 'HM', 'name' => 'Heard and Mc Donald Islands']);
        DB::table('countries')->insert(['code' => 'HN', 'name' => 'Honduras']);
        DB::table('countries')->insert(['code' => 'HK', 'name' => 'Hong Kong']);
        DB::table('countries')->insert(['code' => 'HU', 'name' => 'Hungary']);
        DB::table('countries')->insert(['code' => 'IS', 'name' => 'Iceland']);
        DB::table('countries')->insert(['code' => 'IN', 'name' => 'India']);
        DB::table('countries')->insert(['code' => 'IM', 'name' => 'Isle of Man']);
        DB::table('countries')->insert(['code' => 'ID', 'name' => 'Indonesia']);
        DB::table('countries')->insert(['code' => 'IR', 'name' => 'Iran (Islamic Republic of)']);
        DB::table('countries')->insert(['code' => 'IQ', 'name' => 'Iraq']);
        DB::table('countries')->insert(['code' => 'IE', 'name' => 'Ireland']);
        DB::table('countries')->insert(['code' => 'IL', 'name' => 'Israel']);
        DB::table('countries')->insert(['code' => 'IT', 'name' => 'Italy']);
        DB::table('countries')->insert(['code' => 'CI', 'name' => 'Ivory Coast']);
        DB::table('countries')->insert(['code' => 'JE', 'name' => 'Jersey']);
        DB::table('countries')->insert(['code' => 'JM', 'name' => 'Jamaica']);
        DB::table('countries')->insert(['code' => 'JP', 'name' => 'Japan']);
        DB::table('countries')->insert(['code' => 'JO', 'name' => 'Jordan']);
        DB::table('countries')->insert(['code' => 'KZ', 'name' => 'Kazakhstan']);
        DB::table('countries')->insert(['code' => 'KE', 'name' => 'Kenya']);
        DB::table('countries')->insert(['code' => 'KI', 'name' => 'Kiribati']);
        DB::table('countries')->insert(['code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of']);
        DB::table('countries')->insert(['code' => 'KR', 'name' => 'Korea, Republic of']);
        DB::table('countries')->insert(['code' => 'XK', 'name' => 'Kosovo']);
        DB::table('countries')->insert(['code' => 'KW', 'name' => 'Kuwait']);
        DB::table('countries')->insert(['code' => 'KG', 'name' => 'Kyrgyzstan']);
        DB::table('countries')->insert(['code' => 'LA', 'name' => 'Lao People\'s Democratic Republic']);
        DB::table('countries')->insert(['code' => 'LV', 'name' => 'Latvia']);
        DB::table('countries')->insert(['code' => 'LB', 'name' => 'Lebanon']);
        DB::table('countries')->insert(['code' => 'LS', 'name' => 'Lesotho']);
        DB::table('countries')->insert(['code' => 'LR', 'name' => 'Liberia']);
        DB::table('countries')->insert(['code' => 'LY', 'name' => 'Libyan Arab Jamahiriya']);
        DB::table('countries')->insert(['code' => 'LI', 'name' => 'Liechtenstein']);
        DB::table('countries')->insert(['code' => 'LT', 'name' => 'Lithuania']);
        DB::table('countries')->insert(['code' => 'LU', 'name' => 'Luxembourg']);
        DB::table('countries')->insert(['code' => 'MO', 'name' => 'Macau']);
        DB::table('countries')->insert(['code' => 'MK', 'name' => 'Macedonia']);
        DB::table('countries')->insert(['code' => 'MG', 'name' => 'Madagascar']);
        DB::table('countries')->insert(['code' => 'MW', 'name' => 'Malawi']);
        DB::table('countries')->insert(['code' => 'MY', 'name' => 'Malaysia']);
        DB::table('countries')->insert(['code' => 'MV', 'name' => 'Maldives']);
        DB::table('countries')->insert(['code' => 'ML', 'name' => 'Mali']);
        DB::table('countries')->insert(['code' => 'MT', 'name' => 'Malta']);
        DB::table('countries')->insert(['code' => 'MH', 'name' => 'Marshall Islands']);
        DB::table('countries')->insert(['code' => 'MQ', 'name' => 'Martinique']);
        DB::table('countries')->insert(['code' => 'MR', 'name' => 'Mauritania']);
        DB::table('countries')->insert(['code' => 'MU', 'name' => 'Mauritius']);
        DB::table('countries')->insert(['code' => 'TY', 'name' => 'Mayotte']);
        DB::table('countries')->insert(['code' => 'MX', 'name' => 'Mexico']);
        DB::table('countries')->insert(['code' => 'FM', 'name' => 'Micronesia, Federated States of']);
        DB::table('countries')->insert(['code' => 'MD', 'name' => 'Moldova, Republic of']);
        DB::table('countries')->insert(['code' => 'MC', 'name' => 'Monaco']);
        DB::table('countries')->insert(['code' => 'MN', 'name' => 'Mongolia']);
        DB::table('countries')->insert(['code' => 'ME', 'name' => 'Montenegro']);
        DB::table('countries')->insert(['code' => 'MS', 'name' => 'Montserrat']);
        DB::table('countries')->insert(['code' => 'MA', 'name' => 'Morocco']);
        DB::table('countries')->insert(['code' => 'MZ', 'name' => 'Mozambique']);
        DB::table('countries')->insert(['code' => 'MM', 'name' => 'Myanmar']);
        DB::table('countries')->insert(['code' => 'NA', 'name' => 'Namibia']);
        DB::table('countries')->insert(['code' => 'NR', 'name' => 'Nauru']);
        DB::table('countries')->insert(['code' => 'NP', 'name' => 'Nepal']);
        DB::table('countries')->insert(['code' => 'NL', 'name' => 'Netherlands']);
        DB::table('countries')->insert(['code' => 'AN', 'name' => 'Netherlands Antilles']);
        DB::table('countries')->insert(['code' => 'NC', 'name' => 'New Caledonia']);
        DB::table('countries')->insert(['code' => 'NZ', 'name' => 'New Zealand']);
        DB::table('countries')->insert(['code' => 'NI', 'name' => 'Nicaragua']);
        DB::table('countries')->insert(['code' => 'NE', 'name' => 'Niger']);
        DB::table('countries')->insert(['code' => 'NG', 'name' => 'Nigeria']);
        DB::table('countries')->insert(['code' => 'NU', 'name' => 'Niue']);
        DB::table('countries')->insert(['code' => 'NF', 'name' => 'Norfolk Island']);
        DB::table('countries')->insert(['code' => 'MP', 'name' => 'Northern Mariana Islands']);
        DB::table('countries')->insert(['code' => 'NO', 'name' => 'Norway']);
        DB::table('countries')->insert(['code' => 'OM', 'name' => 'Oman']);
        DB::table('countries')->insert(['code' => 'PK', 'name' => 'Pakistan']);
        DB::table('countries')->insert(['code' => 'PW', 'name' => 'Palau']);
        DB::table('countries')->insert(['code' => 'PS', 'name' => 'Palestine']);
        DB::table('countries')->insert(['code' => 'PA', 'name' => 'Panama']);
        DB::table('countries')->insert(['code' => 'PG', 'name' => 'Papua New Guinea']);
        DB::table('countries')->insert(['code' => 'PY', 'name' => 'Paraguay']);
        DB::table('countries')->insert(['code' => 'PE', 'name' => 'Peru']);
        DB::table('countries')->insert(['code' => 'PH', 'name' => 'Philippines']);
        DB::table('countries')->insert(['code' => 'PN', 'name' => 'Pitcairn']);
        DB::table('countries')->insert(['code' => 'PL', 'name' => 'Poland']);
        DB::table('countries')->insert(['code' => 'PT', 'name' => 'Portugal']);
        DB::table('countries')->insert(['code' => 'PR', 'name' => 'Puerto Rico']);
        DB::table('countries')->insert(['code' => 'QA', 'name' => 'Qatar']);
        DB::table('countries')->insert(['code' => 'RE', 'name' => 'Reunion']);
        DB::table('countries')->insert(['code' => 'RO', 'name' => 'Romania']);
        DB::table('countries')->insert(['code' => 'RU', 'name' => 'Russian Federation']);
        DB::table('countries')->insert(['code' => 'RW', 'name' => 'Rwanda']);
        DB::table('countries')->insert(['code' => 'KN', 'name' => 'Saint Kitts and Nevis']);
        DB::table('countries')->insert(['code' => 'LC', 'name' => 'Saint Lucia']);
        DB::table('countries')->insert(['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines']);
        DB::table('countries')->insert(['code' => 'WS', 'name' => 'Samoa']);
        DB::table('countries')->insert(['code' => 'SM', 'name' => 'San Marino']);
        DB::table('countries')->insert(['code' => 'ST', 'name' => 'Sao Tome and Principe']);
        DB::table('countries')->insert(['code' => 'SA', 'name' => 'Saudi Arabia']);
        DB::table('countries')->insert(['code' => 'SN', 'name' => 'Senegal']);
        DB::table('countries')->insert(['code' => 'RS', 'name' => 'Serbia']);
        DB::table('countries')->insert(['code' => 'SC', 'name' => 'Seychelles']);
        DB::table('countries')->insert(['code' => 'SL', 'name' => 'Sierra Leone']);
        DB::table('countries')->insert(['code' => 'SG', 'name' => 'Singapore']);
        DB::table('countries')->insert(['code' => 'SK', 'name' => 'Slovakia']);
        DB::table('countries')->insert(['code' => 'SI', 'name' => 'Slovenia']);
        DB::table('countries')->insert(['code' => 'SB', 'name' => 'Solomon Islands']);
        DB::table('countries')->insert(['code' => 'SO', 'name' => 'Somalia']);
        DB::table('countries')->insert(['code' => 'ZA', 'name' => 'South Africa']);
        DB::table('countries')->insert(['code' => 'GS', 'name' => 'South Georgia South Sandwich Islands']);
        DB::table('countries')->insert(['code' => 'SS', 'name' => 'South Sudan']);
        DB::table('countries')->insert(['code' => 'ES', 'name' => 'Spain']);
        DB::table('countries')->insert(['code' => 'LK', 'name' => 'Sri Lanka']);
        DB::table('countries')->insert(['code' => 'SH', 'name' => 'St. Helena']);
        DB::table('countries')->insert(['code' => 'PM', 'name' => 'St. Pierre and Miquelon']);
        DB::table('countries')->insert(['code' => 'SD', 'name' => 'Sudan']);
        DB::table('countries')->insert(['code' => 'SR', 'name' => 'Suriname']);
        DB::table('countries')->insert(['code' => 'SJ', 'name' => 'Svalbard and Jan Mayen Islands']);
        DB::table('countries')->insert(['code' => 'SZ', 'name' => 'Swaziland']);
        DB::table('countries')->insert(['code' => 'SE', 'name' => 'Sweden']);
        DB::table('countries')->insert(['code' => 'CH', 'name' => 'Switzerland']);
        DB::table('countries')->insert(['code' => 'SY', 'name' => 'Syrian Arab Republic']);
        DB::table('countries')->insert(['code' => 'TW', 'name' => 'Taiwan']);
        DB::table('countries')->insert(['code' => 'TJ', 'name' => 'Tajikistan']);
        DB::table('countries')->insert(['code' => 'TZ', 'name' => 'Tanzania, United Republic of']);
        DB::table('countries')->insert(['code' => 'TH', 'name' => 'Thailand']);
        DB::table('countries')->insert(['code' => 'TG', 'name' => 'Togo']);
        DB::table('countries')->insert(['code' => 'TK', 'name' => 'Tokelau']);
        DB::table('countries')->insert(['code' => 'TO', 'name' => 'Tonga']);
        DB::table('countries')->insert(['code' => 'TT', 'name' => 'Trinidad and Tobago']);
        DB::table('countries')->insert(['code' => 'TN', 'name' => 'Tunisia']);
        DB::table('countries')->insert(['code' => 'TR', 'name' => 'Turkey']);
        DB::table('countries')->insert(['code' => 'TM', 'name' => 'Turkmenistan']);
        DB::table('countries')->insert(['code' => 'TC', 'name' => 'Turks and Caicos Islands']);
        DB::table('countries')->insert(['code' => 'TV', 'name' => 'Tuvalu']);
        DB::table('countries')->insert(['code' => 'UG', 'name' => 'Uganda']);
        DB::table('countries')->insert(['code' => 'UA', 'name' => 'Ukraine']);
        DB::table('countries')->insert(['code' => 'AE', 'name' => 'United Arab Emirates']);
        DB::table('countries')->insert(['code' => 'GB', 'name' => 'United Kingdom']);
        DB::table('countries')->insert(['code' => 'US', 'name' => 'United States']);
        DB::table('countries')->insert(['code' => 'UM', 'name' => 'United States minor outlying islands']);
        DB::table('countries')->insert(['code' => 'UY', 'name' => 'Uruguay']);
        DB::table('countries')->insert(['code' => 'UZ', 'name' => 'Uzbekistan']);
        DB::table('countries')->insert(['code' => 'VU', 'name' => 'Vanuatu']);
        DB::table('countries')->insert(['code' => 'VA', 'name' => 'Vatican City State']);
        DB::table('countries')->insert(['code' => 'VE', 'name' => 'Venezuela']);
        DB::table('countries')->insert(['code' => 'VN', 'name' => 'Vietnam']);
        DB::table('countries')->insert(['code' => 'VG', 'name' => 'Virgin Islands (British)']);
        DB::table('countries')->insert(['code' => 'VI', 'name' => 'Virgin Islands (U.S.)']);
        DB::table('countries')->insert(['code' => 'WF', 'name' => 'Wallis and Futuna Islands']);
        DB::table('countries')->insert(['code' => 'EH', 'name' => 'Western Sahara']);
        DB::table('countries')->insert(['code' => 'YE', 'name' => 'Yemen']);
        DB::table('countries')->insert(['code' => 'ZR', 'name' => 'Zaire']);
        DB::table('countries')->insert(['code' => 'ZM', 'name' => 'Zambia']);
        DB::table('countries')->insert(['code' => 'ZW', 'name' => 'Zimbabwe']);
    }
}
